02/24/2026

In [1]:
import numpy as np
import time

In [2]:
def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
    return x, max_iterations
    
    
def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i)) # Using already updated values
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n)) # Using old values
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
    return x, max_iterations

In [3]:
# Challenge A

A = np.array([
	[0.582745, 0.48	, 0.10	, 0.  	, 0.  	], 
 [0.48	, 1.044129, 0.46	, 0.10	, 0.  	],
 [0.10	, 0.46	, 1.10431 , 0.44	, 0.10	],
 [0.  	, 0.10	, 0.44	, 0.963889, 0.42	],
 [0.  	, 0.  	, 0.10	, 0.42	, 0.522565]], dtype=float)
b = np.array([1.162745, 2.084129, 2.20431 , 1.923889, 1.042565], dtype=float)

x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100

# Jacobi
solution, iterations = jacobi(A, b, x0, tol, max_iterations)
print(f"Solution: {solution}")
print(f"Iterations: {iterations}\n")

# Gauss-Seidel
solution, iterations = gauss_seidel(A, b,x0, tol, max_iterations)
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")

Solution: [0.34253948 0.34219824 0.34215212 0.34233398 0.34277892]
Iterations: 100

Solution: [0.99999926 1.00000045 0.99999989 0.99999997 1.00000005]
Iterations: 20


In [4]:
# Challenge B

A = np.array([[1, 	1], [1, 1.0001]])
b = np.array([1, 1])

x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100

# Jacobi
solution, iterations = jacobi(A, b, x0, tol, max_iterations)
print(f"Solution: {solution}")
print(f"Iterations: {iterations}\n")

# Gauss-Seidel
solution, iterations = gauss_seidel(A, b,x0, tol, max_iterations)
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")

Solution: [1 0]
Iterations: 1

Solution: [1 0]
Iterations: 1


In [5]:
# Challenge C

A = np.array([[1, 1], [1, 1.0001]])
b = np.array([1, 1.0001])

x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100

# Jacobi
solution, iterations = jacobi(A, b, x0, tol, max_iterations)
print(f"Solution: {solution}")
print(f"Iterations: {iterations}\n")

# Gauss-Seidel
solution, iterations = gauss_seidel(A, b,x0, tol, max_iterations)
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")

Solution: [0.         0.00498727]
Iterations: 100

Solution: [0.99014933 0.00994967]
Iterations: 100


This did not converge.

In [6]:
def diagonallyDominant(A):
    print("A:\n", A)
    print("\nIs the matrix diagonally dominant?")
    
    for i in range (0, len(A)): # i represents the row number; diagonal element where row num = column num
        
        if np.abs(A[i,i]) < np.sum(np.abs(A[i])) - np.abs(A[i,i]):  
                        # sum of elements in row i - diagonal

            return False # if the abs value of the diagonal element is less than the absolute value of the sum of other elements
                         # in the row, the matrix is not diagonally dominant
        
    return True # otherwise, the diagonal element was never less than the sum of the other elements,
                # so the matrix IS diagonally dominant

In [7]:
A = np.array([
	[0.582745, 0.48	, 0.10	, 0.  	, 0.  	], 
 [0.48	, 1.044129, 0.46	, 0.10	, 0.  	],
 [0.10	, 0.46	, 1.10431 , 0.44	, 0.10	],
 [0.  	, 0.10	, 0.44	, 0.963889, 0.42	],
 [0.  	, 0.  	, 0.10	, 0.42	, 0.522565]], dtype=float)

diagonallyDominant(A)

A:
 [[0.582745 0.48     0.1      0.       0.      ]
 [0.48     1.044129 0.46     0.1      0.      ]
 [0.1      0.46     1.10431  0.44     0.1     ]
 [0.       0.1      0.44     0.963889 0.42    ]
 [0.       0.       0.1      0.42     0.522565]]

Is the matrix diagonally dominant?


True

In [8]:
A = np.array([[1., 2., 3., 0., 0.],[2., 1., 2., 3., 0.],[3., 2., 1., 2., 3.],[0., 3., 2., 1., 2.],[0., 0., 3., 2., 1.]])

diagonallyDominant(A)

A:
 [[1. 2. 3. 0. 0.]
 [2. 1. 2. 3. 0.]
 [3. 2. 1. 2. 3.]
 [0. 3. 2. 1. 2.]
 [0. 0. 3. 2. 1.]]

Is the matrix diagonally dominant?


False