02/26/2026

In [2]:
import numpy as np

# Data points
X = np.array([1, 2, 3, 4, 5])
Y = np.array([1.2, 2.8, 3.6, 4.5, 5.1])

# Stack the design matrix with a column of ones (for the intercept)
A = np.vstack([X, np.ones(len(X))]).T

print("X:\n", X)
print("Y:\n", Y)
print("A:\n", A)

# Solve using least squares
m, c = np.linalg.lstsq(A, Y, rcond=None)[0]
print(f"\nSlope: {m}, Intercept: {c}")

X:
 [1 2 3 4 5]
Y:
 [1.2 2.8 3.6 4.5 5.1]
A:
 [[1. 1.]
 [2. 1.]
 [3. 1.]
 [4. 1.]
 [5. 1.]]

Slope: 0.9500000000000001, Intercept: 0.5900000000000001
