02/12/2026

In [1]:
import numpy as np

In [2]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [3]:
print(v1)
print(v2)

[1 2 3]
[4 5 6]


In [4]:
v_add = v1 + v2
v_sub = v1 - v2

In [5]:
print("v1 + v2 =", v_add)
print("v1 - v2 =", v_sub)

v1 + v2 = [5 7 9]
v1 - v2 = [-3 -3 -3]


In [6]:
scalar = 2
v_scale = (scalar * v1)

In [7]:
print("v1 * 2 =", v_scale)

v1 * 2 = [2 4 6]


In [9]:
dot_product = np.dot(v1, v2)
print("v1 * v2 =", dot_product)

v1 * v2 = 32


In [10]:
magnitude_v1 = np.linalg.norm(v1)
magnitude_v2 = np.linalg.norm(v2)

print(magnitude_v1)
print(magnitude_v2)

3.7416573867739413
8.774964387392123


In [13]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])

print(A, "\n")
print(B)

[[1 2 3]
 [4 5 6]] 

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [16]:
C = np.array([[1, 2, 3], [4, 5, 6]])
matrix_add = A + C
matrix_sub = A - C

print("A + C =\n", matrix_add)
print("A - C =\n", matrix_sub)

A + C =
 [[ 2  4  6]
 [ 8 10 12]]
A - C =
 [[0 0 0]
 [0 0 0]]


In [17]:
transpose_A = A.T

print(A, "\n")
print(transpose_A)

[[1 2 3]
 [4 5 6]] 

[[1 4]
 [2 5]
 [3 6]]


In [19]:
A = np.array([[2, 1], [1, 2]])
e_value, e_vector = np.linalg.eig(A)
print("eiganvalue:", e_value)
print("eigenvector:\n", e_vector)

eiganvalue: [3. 1.]
eigenvector:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [20]:
A = np.array([[4, 7], [2,6]])
A_inverse = np.linalg.inv(A)
print(A, "\n")
print(A_inverse)

[[4 7]
 [2 6]] 

[[ 0.6 -0.7]
 [-0.2  0.4]]


In [21]:
identity = np.dot(A, A_inverse)
print(identity)

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
