02/12/2026

In [1]:
import numpy as np

In [2]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

In [3]:
print(v1)
print(v2)

[1 2 3]
[4 5 6]


In [4]:
v_add = v1 + v2
v_sub = v1 - v2

In [5]:
print("v1 + v2 =", v_add)
print("v1 - v2 =", v_sub)

v1 + v2 = [5 7 9]
v1 - v2 = [-3 -3 -3]


In [6]:
scalar = 2
v_scale = (scalar * v1)

In [7]:
print("v1 * 2 =", v_scale)

v1 * 2 = [2 4 6]


In [9]:
dot_product = np.dot(v1, v2)
print("v1 * v2 =", dot_product)

v1 * v2 = 32


In [10]:
magnitude_v1 = np.linalg.norm(v1)
magnitude_v2 = np.linalg.norm(v2)

print(magnitude_v1)
print(magnitude_v2)

3.7416573867739413
8.774964387392123


In [13]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])

print(A, "\n")
print(B)

[[1 2 3]
 [4 5 6]] 

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [16]:
C = np.array([[1, 2, 3], [4, 5, 6]])
matrix_add = A + C
matrix_sub = A - C

print("A + C =\n", matrix_add)
print("A - C =\n", matrix_sub)

A + C =
 [[ 2  4  6]
 [ 8 10 12]]
A - C =
 [[0 0 0]
 [0 0 0]]


In [17]:
transpose_A = A.T

print(A, "\n")
print(transpose_A)

[[1 2 3]
 [4 5 6]] 

[[1 4]
 [2 5]
 [3 6]]


In [19]:
A = np.array([[2, 1], [1, 2]])
e_value, e_vector = np.linalg.eig(A)
print("eiganvalue:", e_value)
print("eigenvector:\n", e_vector)

eiganvalue: [3. 1.]
eigenvector:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [20]:
A = np.array([[4, 7], [2,6]])
A_inverse = np.linalg.inv(A)
print(A, "\n")
print(A_inverse)

[[4 7]
 [2 6]] 

[[ 0.6 -0.7]
 [-0.2  0.4]]


In [21]:
identity = np.dot(A, A_inverse)
print(identity)

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


02/17/2026

In [22]:
import numpy as np
def gaussian_elimination(A, b):
    n = len(b)
    # Forward elimination
    for i in range(n):
        # Pivoting
        max_row = max(range(i, n), key=lambda x: abs(A[x][i]))
        A[i], A[max_row] = A[max_row], A[i]
        b[i], b[max_row] = b[max_row], b[i]

        # Make the rows below this one 0 in current column
        for j in range(i + 1, n):
            ratio = A[j][i] / A[i][i]
            A[j] = [A[j][k] - ratio * A[i][k] for k in range(n)]
            b[j] -= ratio * b[i]
            
    # Backward substitution
    x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - sum(A[i][j] * x[j] for j in range(i + 1, n))) / A[i][i]
    return x

In [23]:
# Example Usage
A = [[3, 2, -4], [2, 3, 3], [5, -3, 1]]
b = [3, 15, 14]
solution = gaussian_elimination(A, b)
print(f"Solution: {solution}")

Solution: [2.9999999999999996, 0.9999999999999996, 2.0]


In [25]:
# Example Usage
A = [[2, 3, -1], [4, -2, 2], [-2, 1, 2]]
b = [5, 6, -1]
solution = gaussian_elimination(A, b)
print(f"Solution: {solution}")

Solution: [1.5833333333333333, 0.8333333333333333, 0.6666666666666666]


In [26]:
ans = np.linalg.solve(A,b)
print(ans)

[1.58333333 0.83333333 0.66666667]


In [37]:
#LU Decomposition

import numpy as np

def lu_decomposition(A):
    n = len(A)
    L = np.eye(n) # Initialize L as an identity matrix
    U = np.array(A, dtype=float) # Copy of A to avoid modifying the original matrix
    
    for i in range(n):
        # Eliminate elements below the pivot (U[i, i])
        for j in range(i+1, n):
            if U[i, i] == 0:
                raise ValueError("Zero pivot encountered. LU decomposition cannot proceed.")
            
            factor = U[j, i] / U[i, i] # Multiplier for row operation
            L[j, i] = factor # Store multiplier in L
            
            # Update the rows of U
            for k in range(i, n):
                U[j, k] -= factor * U[i, k]
    return L, U

In [34]:
# Example usage
A = np.array([[2, 3, 1],[4, 7, -1],[-2, 1, 2]])

L, U = lu_decomposition(A)

print("Matrix A:\n", A)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)

Matrix A:
 [[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]]
Lower Triangular Matrix L:
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  4.  1.]]
Upper Triangular Matrix U:
 [[ 2.  3.  1.]
 [ 0.  1. -3.]
 [ 0.  0. 15.]]


In [36]:
import numpy as np
from scipy.linalg import lu

# Example matrix
A = np.array([[2, 3, 1],
[4, 7, -1],
[-2, 1, 2]])

P, L, U = lu(A)

print("Matrix A:\n", A)
print("Permutation Matrix P:\n", P)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)

Matrix A:
 [[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]]
Permutation Matrix P:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
Lower Triangular Matrix L:
 [[ 1.          0.          0.        ]
 [-0.5         1.          0.        ]
 [ 0.5        -0.11111111  1.        ]]
Upper Triangular Matrix U:
 [[ 4.          7.         -1.        ]
 [ 0.          4.5         1.5       ]
 [ 0.          0.          1.66666667]]


In [39]:
print(L*U, "\n")
print(np.matmul(L, U)) # or L @ U

[[ 4.          0.         -0.        ]
 [-0.          4.5         0.        ]
 [ 0.         -0.          1.66666667]] 

[[ 4.  7. -1.]
 [-2.  1.  2.]
 [ 2.  3.  1.]]


In [40]:
print(A)

# multiply P @ A to get back original matrix
# P shows what values you swapped
print(P@A)

[[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]]
[[-2.  1.  2.]
 [ 2.  3.  1.]
 [ 4.  7. -1.]]


02/19/2026

In [48]:
import numpy as np
def jacobi(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    print(x)
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - s) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        print(x_new)
        x = x_new
    return x, max_iterations

In [49]:
# Example usage
A = np.array([[4, -1, 0, 0],[-1, 4, -1, 0],[0, -1, 4, -1],[0, 0, -1, 3]])
b = np.array([15, 10, 10, 10])
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100
solution, iterations = jacobi(A, b, x0, tol, max_iterations)
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")

[0 0 0 0]
[3 2 2 3]
[4 3 3 4]
[4 4 4 4]
Solution: [4 4 4 4]
Iterations: 3


In [52]:
import numpy as np
def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            s1 = sum(A[i][j] * x_new[j] for j in range(i)) # Using already updated values
            s2 = sum(A[i][j] * x[j] for j in range(i + 1, n)) # Using old values
            x_new[i] = (b[i] - s1 - s2) / A[i][i]
        # Check for convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, k
        x = x_new
    return x, max_iterations

In [53]:
# Example usage
A = np.array([[4, -1, 0, 0],[-1, 4, -1, 0],[0, -1, 4, -1],[0, 0, -1, 3]])
b = np.array([15, 10, 10, 10])
x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100
solution, iterations = gauss_seidel(A, b, x0, tol, max_iterations)
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")

[0 0 0 0]
Solution: [4 4 4 4]
Iterations: 2


02/24/2026

In [54]:
import numpy as np
A = np.array([[2,1],[1,1]])
B = np.array([[2,4],[1,2]]) # rows are multiples of eachother
print(np.linalg.det(A))
print(np.linalg.det(B))

1.0
0.0


In [57]:
Ainv = np.linalg.inv(A)

print(Ainv)

[[ 1. -1.]
 [-1.  2.]]


In [58]:
Binv = np.linalg.inv(B)

print(Binv)

LinAlgError: Singular matrix

In [66]:
print("A:\n", A)
kappa = np.linalg.cond(A, 2)
print("\nk(A) =", kappa)

A:
 [[0.582745 0.48     0.1      0.       0.      ]
 [0.48     1.044129 0.46     0.1      0.      ]
 [0.1      0.46     1.10431  0.44     0.1     ]
 [0.       0.1      0.44     0.963889 0.42    ]
 [0.       0.       0.1      0.42     0.522565]]

k(A) = 8.067443024472189


In [60]:
A = np.array([[1, 	1], [1, 1.0001]])
b = np.array([1, 1.0001])

x0 = np.zeros_like(b)
tol = 1e-6
max_iterations = 100

# Jacobi
solution, iterations = jacobi(A, b, x0, tol, max_iterations)
print(f"Solution: {solution}")
print(f"Iterations: {iterations}\n")

# Gauss-Seidel
solution, iterations = gauss_seidel(A, b,x0, tol, max_iterations)
print(f"Solution: {solution}")
print(f"Iterations: {iterations}")

[0. 0.]
[1. 1.]
[0.0000000e+00 9.9990001e-05]
[0.99990001 1.        ]
[0.         0.00019997]
[0.99980003 1.        ]
[0.         0.00029994]
[0.99970006 1.        ]
[0.        0.0003999]
[0.9996001 1.       ]
[0.         0.00049985]
[0.99950015 1.        ]
[0.         0.00059979]
[0.99940021 1.        ]
[0.         0.00069972]
[0.99930028 1.        ]
[0.         0.00079964]
[0.99920036 1.        ]
[0.         0.00089955]
[0.99910045 1.        ]
[0.         0.00099945]
[0.99900055 1.        ]
[0.         0.00109934]
[0.99890066 1.        ]
[0.         0.00119922]
[0.99880078 1.        ]
[0.         0.00129909]
[0.99870091 1.        ]
[0.         0.00139895]
[0.99860105 1.        ]
[0.        0.0014988]
[0.9985012 1.       ]
[0.         0.00159864]
[0.99840136 1.        ]
[0.         0.00169847]
[0.99830153 1.        ]
[0.         0.00179829]
[0.99820171 1.        ]
[0.        0.0018981]
[0.9981019 1.       ]
[0.        0.0019979]
[0.9980021 1.       ]
[0.         0.00209769]
[0.9979023

In [65]:
A = np.array([
	[0.582745, 0.48	, 0.10	, 0.  	, 0.  	], 
 [0.48	, 1.044129, 0.46	, 0.10	, 0.  	],
 [0.10	, 0.46	, 1.10431 , 0.44	, 0.10	],
 [0.  	, 0.10	, 0.44	, 0.963889, 0.42	],
 [0.  	, 0.  	, 0.10	, 0.42	, 0.522565]], dtype=float)

print("A:\n", A)
kappa = np.linalg.cond(A, 2)
print("\nk(A) =", kappa)

A:
 [[0.582745 0.48     0.1      0.       0.      ]
 [0.48     1.044129 0.46     0.1      0.      ]
 [0.1      0.46     1.10431  0.44     0.1     ]
 [0.       0.1      0.44     0.963889 0.42    ]
 [0.       0.       0.1      0.42     0.522565]]

k(A) = 8.067443024472189
